apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  destination:
    namespace: mongodb
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: mongodb-kubernetes
    repoURL: https://mongodb.github.io/helm-charts
    targetRevision: '*'
    helm:
      valuesObject:
        operator:
          watchedResources:
            - mongodbcommunity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
